name: insta
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.3
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  photo_manager: ^2.8.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/background/
