// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvz1kUzLI3VFXoziDoNm9sy7L4Y-r7Bc',
    appId: '1:316065604613:web:e0beff94588b1ee797286c',
    messagingSenderId: '316065604613',
    projectId: 'instaclone-9d80c',
    authDomain: 'instaclone-9d80c.firebaseapp.com',
    storageBucket: 'instaclone-9d80c.appspot.com',
    measurementId: 'G-039K9KP7PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0kspkWTEiAKLTO0r25sHtNnSWVwYZ2Q',
    appId: '1:316065604613:android:3a4c2110c4071a1097286c',
    messagingSenderId: '316065604613',
    projectId: 'instaclone-9d80c',
    storageBucket: 'instaclone-9d80c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4XzCwE-GWTyO6zHktXw7EeOjkEkUSfg',
    appId: '1:316065604613:ios:7edd15ac91fb9c4c97286c',
    messagingSenderId: '316065604613',
    projectId: 'instaclone-9d80c',
    storageBucket: 'instaclone-9d80c.appspot.com',
    iosBundleId: 'com.example.insta',
  );
}
